### ISSUE TITLE
Component Cover Image cannot be deleted

### ISSUE THREAD

**Issue by tanushree57** [judemanutd/octa-angular-backend-portal#46]
Once a cover image is uploaded for a component, it cannot be deleted.

**Comment by ajay-octalogic** [comment]
DELETE REQUEST: 
https://us-central1-octalogic-portfolio-dev.cloudfunctions.net/api/v1/admin/project/6c281d99-b356-4f4b-8b20-47be5b1329cc/component/4b8b3c6d-9426-4384-b79a-aaf0d10a85fd/cover

Response:
{"error":{"code":404,"message":"Entity not found","application_code":null}}

**Comment by judemanutd** [comment]
Resolved in https://github.com/judemanutd/octa-api-server/issues/87
